name: GitHub Actions Demo
on: [push] # Triggers the workflow every time you push code
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "GitHub Actions is successfully running!"
