name: GitHub Actions Demo
on: [push]
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Your first action step
      - name: Run a one-line script
        run: echo "GitHub Actions is successfully running!"

      # YOUR NEW STEP HERE
      - name: Run another action step
        : echo "This is my second action running in the same job!"
